include:
  - project: 'workloads/ci-template'
    ref: master
    file: '/gitlab-ci.v4.1.yaml'

variables:
  IMAGE_REPOSITORY: asia.gcr.io/teko-registry/loyalty-system/loyalty-file-processing
  GOPRIVATE: git.teko.vn,*.tekoapis.com
  GOSUMDB: "off"

# Unitest cases
test:unitest:
  stage: pretest
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /merge_request_event|parent_pipeline/
    - if: $CI_PIPELINE_SOURCE =~ /web|push|parent_pipeline/ && $CI_COMMIT_REF_NAME =~ /master|main|^releases\/(\d+\.\d+\.\d+)(-.*)?/ && $CI_COMMIT_MESSAGE !~ /^Merge branch.*/
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  image: golang:1.19-buster
  services:
    - mysql:8.0
  variables:
    MYSQL_HOST: mysql
    MYSQL_DATABASE: loyalty_file_process_service_test
    MYSQL_ROOT_PASSWORD: 1
    MYSQL_PORT: 3306
    MYSQL_USERNAME: root
    MYSQL_PASSWORD: 1 # pragma: whitelist secret
    ENV: test
  before_script:
    - git config --global http.sslVerify false
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.teko.vn".insteadOf "https://git.teko.vn"
    - go mod download
    - cp config.tmp.yml config.yml
  script:
    - go test ./... -coverprofile=loyalty-file-processing-coverage.cov.tmp -coverpkg=./... -covermode count
    - cat loyalty-file-processing-coverage.cov.tmp | grep -v -e"internal/ent" -e"/cmd" -e "/configs" > loyalty-file-processing-coverage.cov
    - go tool cover -func=loyalty-file-processing-coverage.cov
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < loyalty-file-processing-coverage.cov > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/total:\t.*\(statements\)\t.*\d+(?:\.\d+)?/'