server:
  http:
    host: localhost
    port: 10080

database:
  mysql:
    db_name: loyalty_file_process_service
    host: localhost
    port: 3306
    username: loyalty_file_process_service
    password: 1 # --no-verify
    options: parseTime=true

logger:
  console: true
  format_json: false
  level: debug

job:
  award_point:
    schedule: '0/5 * * * *' # every 5 minutes at first minute

provider_config:
  loyalty:
    endpoint: http://localhost:8080
    x_api_key: _need_to_fill_api_key_
    paths:
      txn_get_list: /api/v4/transaction/getListTransaction
      txn_grant: /api/v4/transaction/grantPoint
  file_service:
    endpoint: https://files.dev.tekoapis.net
    paths:
      upload_doc: /upload/doc
      download: /files/{fileId}
      delete: /files/{fileId}
