server:
  http:
    host: localhost
    port: 10080
  api_key: '_api_key_' # should replace api key by K8S Env

database:
  mysql:
    db_name: loyalty_file_process_service
    host: localhost
    port: 3306
    username: loyalty_file_process_service
    password: 1
    options: parseTime=true
  debug:
    enable: false
    ping_cron: '-'

logger:
  console: true
  format_json: false
  level: debug

job:
  award_point:
    schedule: '-' # every 5 minutes at first minute
  update_status_fap:
    schedule: '-' # every 5 minutes at first minute
    max_checking_time: 60 # unit is minutes
  file_processing:
    schedule: '*/1 * * * *' # every 3 minutes
  flatten:
    schedule: '0 */1 * * * *' # every 1 minutes
    num_digesters: 2
  execute_task:
    schedule: '15 */1 * * * *' # every 1 minutes
    num_digesters: 2
    num_digesters_custom:
      - client_id: 1
        value: 2
      - client_id: 9
        value: 1
  execute_group_task:
    schedule: '30 */1 * * * *' # every 1 minutes
    num_digesters: 2
  update_status:
    schedule: '50 */1 * * * *' # every 1 minutes
    num_digesters: 2

provider_config:
  loyalty:
    endpoint: http://localhost:8080
    x_api_key: _need_to_fill_api_key_
    paths:
      txn_get_list: /api/v4/transaction/getListTransaction
      txn_grant: /api/v4/transaction/grantPoint
  file_service:
    endpoint: https://files.dev.tekoapis.net
    paths:
      upload_doc: /upload/doc
      download: /files/{fileId}
      delete: /files/{fileId}
  f_alt_service:
    app_id: "1234"
    username: "username"
    password: "password"
    master_key: "the_secret_key!"
    session_expired_in: 1 # month
    rest_key: ""
    endpoint: "https://f-alt-server.dev.tekoapis.net/parse"
    is_enable: true
