server:
  http:
    host: localhost
    port: 10080

database:
  mysql:
    db_name: loyalty_file_process_service
    host: localhost
    port: 3306
    username: loyalty_file_process_service
    password: 1
    options: parseTime=true

logger:
  console: true
  format_json: false
  level: debug

job:
  award_point:
    schedule: '0/5 * * * *' # every 5 minutes at first minute
