server:
  http:
    host: localhost
    port: 10080

database:
  mysql:
    db_name: loyalty_file_process_service
    host: localhost
    port: 3306
    username: loyalty_file_process_service
    password: 1

logger:
  console: true
  format_json: false
  level: debug
