// Code generated by ent, DO NOT EDIT.

package processingfile

import (
	"time"
)

const (
	// Label holds the string label denoting the processingfile type in the database.
	Label = "processing_file"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldExtFileRequest holds the string denoting the ext_file_request field in the database.
	FieldExtFileRequest = "ext_file_request"
	// FieldFileURL holds the string denoting the file_url field in the database.
	FieldFileURL = "file_url"
	// FieldResultFileURL holds the string denoting the result_file_url field in the database.
	FieldResultFileURL = "result_file_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFileParameters holds the string denoting the file_parameters field in the database.
	FieldFileParameters = "file_parameters"
	// FieldSellerID holds the string denoting the seller_id field in the database.
	FieldSellerID = "seller_id"
	// FieldTotalMapping holds the string denoting the total_mapping field in the database.
	FieldTotalMapping = "total_mapping"
	// FieldNeedGroupRow holds the string denoting the need_group_row field in the database.
	FieldNeedGroupRow = "need_group_row"
	// FieldStatsTotalRow holds the string denoting the stats_total_row field in the database.
	FieldStatsTotalRow = "stats_total_row"
	// FieldStatsTotalProcessed holds the string denoting the stats_total_processed field in the database.
	FieldStatsTotalProcessed = "stats_total_processed"
	// FieldStatsTotalSuccess holds the string denoting the stats_total_success field in the database.
	FieldStatsTotalSuccess = "stats_total_success"
	// FieldErrorDisplay holds the string denoting the error_display field in the database.
	FieldErrorDisplay = "error_display"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldMerchantID holds the string denoting the merchant_id field in the database.
	FieldMerchantID = "merchant_id"
	// FieldAcceptLanguage holds the string denoting the accept_language field in the database.
	FieldAcceptLanguage = "accept_language"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the processingfile in the database.
	Table = "processing_file"
)

// Columns holds all SQL columns for processingfile fields.
var Columns = []string{
	FieldID,
	FieldClientID,
	FieldDisplayName,
	FieldExtFileRequest,
	FieldFileURL,
	FieldResultFileURL,
	FieldStatus,
	FieldFileParameters,
	FieldSellerID,
	FieldTotalMapping,
	FieldNeedGroupRow,
	FieldStatsTotalRow,
	FieldStatsTotalProcessed,
	FieldStatsTotalSuccess,
	FieldErrorDisplay,
	FieldTenantID,
	FieldMerchantID,
	FieldAcceptLanguage,
	FieldCreatedAt,
	FieldCreatedBy,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// FileURLValidator is a validator for the "file_url" field. It is called by the builders before save.
	FileURLValidator func(string) error
	// DefaultTotalMapping holds the default value on creation for the "total_mapping" field.
	DefaultTotalMapping int32
	// DefaultNeedGroupRow holds the default value on creation for the "need_group_row" field.
	DefaultNeedGroupRow bool
	// DefaultStatsTotalRow holds the default value on creation for the "stats_total_row" field.
	DefaultStatsTotalRow int32
	// DefaultStatsTotalProcessed holds the default value on creation for the "stats_total_processed" field.
	DefaultStatsTotalProcessed int32
	// DefaultStatsTotalSuccess holds the default value on creation for the "stats_total_success" field.
	DefaultStatsTotalSuccess int32
	// DefaultAcceptLanguage holds the default value on creation for the "accept_language" field.
	DefaultAcceptLanguage string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
