// Code generated by ent, DO NOT EDIT.

package processingfile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldClientID), v))
	})
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDisplayName), v))
	})
}

// FileURL applies equality check predicate on the "file_url" field. It's identical to FileURLEQ.
func FileURL(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFileURL), v))
	})
}

// ResultFileURL applies equality check predicate on the "result_file_url" field. It's identical to ResultFileURLEQ.
func ResultFileURL(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldResultFileURL), v))
	})
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int16) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatus), v))
	})
}

// FileParameters applies equality check predicate on the "file_parameters" field. It's identical to FileParametersEQ.
func FileParameters(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFileParameters), v))
	})
}

// TotalMapping applies equality check predicate on the "total_mapping" field. It's identical to TotalMappingEQ.
func TotalMapping(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTotalMapping), v))
	})
}

// StatsTotalRow applies equality check predicate on the "stats_total_row" field. It's identical to StatsTotalRowEQ.
func StatsTotalRow(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatsTotalRow), v))
	})
}

// StatsTotalProcessed applies equality check predicate on the "stats_total_processed" field. It's identical to StatsTotalProcessedEQ.
func StatsTotalProcessed(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatsTotalProcessed), v))
	})
}

// StatsTotalSuccess applies equality check predicate on the "stats_total_success" field. It's identical to StatsTotalSuccessEQ.
func StatsTotalSuccess(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatsTotalSuccess), v))
	})
}

// ErrorDisplay applies equality check predicate on the "error_display" field. It's identical to ErrorDisplayEQ.
func ErrorDisplay(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldErrorDisplay), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedBy), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldClientID), v))
	})
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldClientID), v))
	})
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldClientID), v...))
	})
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldClientID), v...))
	})
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldClientID), v))
	})
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldClientID), v))
	})
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldClientID), v))
	})
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldClientID), v))
	})
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDisplayName), v))
	})
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDisplayName), v))
	})
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDisplayName), v...))
	})
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDisplayName), v...))
	})
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDisplayName), v))
	})
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDisplayName), v))
	})
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDisplayName), v))
	})
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDisplayName), v))
	})
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDisplayName), v))
	})
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDisplayName), v))
	})
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDisplayName), v))
	})
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDisplayName), v))
	})
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDisplayName), v))
	})
}

// FileURLEQ applies the EQ predicate on the "file_url" field.
func FileURLEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFileURL), v))
	})
}

// FileURLNEQ applies the NEQ predicate on the "file_url" field.
func FileURLNEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFileURL), v))
	})
}

// FileURLIn applies the In predicate on the "file_url" field.
func FileURLIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldFileURL), v...))
	})
}

// FileURLNotIn applies the NotIn predicate on the "file_url" field.
func FileURLNotIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldFileURL), v...))
	})
}

// FileURLGT applies the GT predicate on the "file_url" field.
func FileURLGT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFileURL), v))
	})
}

// FileURLGTE applies the GTE predicate on the "file_url" field.
func FileURLGTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFileURL), v))
	})
}

// FileURLLT applies the LT predicate on the "file_url" field.
func FileURLLT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFileURL), v))
	})
}

// FileURLLTE applies the LTE predicate on the "file_url" field.
func FileURLLTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFileURL), v))
	})
}

// FileURLContains applies the Contains predicate on the "file_url" field.
func FileURLContains(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFileURL), v))
	})
}

// FileURLHasPrefix applies the HasPrefix predicate on the "file_url" field.
func FileURLHasPrefix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFileURL), v))
	})
}

// FileURLHasSuffix applies the HasSuffix predicate on the "file_url" field.
func FileURLHasSuffix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFileURL), v))
	})
}

// FileURLEqualFold applies the EqualFold predicate on the "file_url" field.
func FileURLEqualFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFileURL), v))
	})
}

// FileURLContainsFold applies the ContainsFold predicate on the "file_url" field.
func FileURLContainsFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFileURL), v))
	})
}

// ResultFileURLEQ applies the EQ predicate on the "result_file_url" field.
func ResultFileURLEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLNEQ applies the NEQ predicate on the "result_file_url" field.
func ResultFileURLNEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLIn applies the In predicate on the "result_file_url" field.
func ResultFileURLIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldResultFileURL), v...))
	})
}

// ResultFileURLNotIn applies the NotIn predicate on the "result_file_url" field.
func ResultFileURLNotIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldResultFileURL), v...))
	})
}

// ResultFileURLGT applies the GT predicate on the "result_file_url" field.
func ResultFileURLGT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLGTE applies the GTE predicate on the "result_file_url" field.
func ResultFileURLGTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLLT applies the LT predicate on the "result_file_url" field.
func ResultFileURLLT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLLTE applies the LTE predicate on the "result_file_url" field.
func ResultFileURLLTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLContains applies the Contains predicate on the "result_file_url" field.
func ResultFileURLContains(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLHasPrefix applies the HasPrefix predicate on the "result_file_url" field.
func ResultFileURLHasPrefix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLHasSuffix applies the HasSuffix predicate on the "result_file_url" field.
func ResultFileURLHasSuffix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLEqualFold applies the EqualFold predicate on the "result_file_url" field.
func ResultFileURLEqualFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldResultFileURL), v))
	})
}

// ResultFileURLContainsFold applies the ContainsFold predicate on the "result_file_url" field.
func ResultFileURLContainsFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldResultFileURL), v))
	})
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int16) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatus), v))
	})
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int16) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatus), v))
	})
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int16) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldStatus), v...))
	})
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int16) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldStatus), v...))
	})
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int16) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatus), v))
	})
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int16) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatus), v))
	})
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int16) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatus), v))
	})
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int16) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatus), v))
	})
}

// FileParametersEQ applies the EQ predicate on the "file_parameters" field.
func FileParametersEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFileParameters), v))
	})
}

// FileParametersNEQ applies the NEQ predicate on the "file_parameters" field.
func FileParametersNEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFileParameters), v))
	})
}

// FileParametersIn applies the In predicate on the "file_parameters" field.
func FileParametersIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldFileParameters), v...))
	})
}

// FileParametersNotIn applies the NotIn predicate on the "file_parameters" field.
func FileParametersNotIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldFileParameters), v...))
	})
}

// FileParametersGT applies the GT predicate on the "file_parameters" field.
func FileParametersGT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFileParameters), v))
	})
}

// FileParametersGTE applies the GTE predicate on the "file_parameters" field.
func FileParametersGTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFileParameters), v))
	})
}

// FileParametersLT applies the LT predicate on the "file_parameters" field.
func FileParametersLT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFileParameters), v))
	})
}

// FileParametersLTE applies the LTE predicate on the "file_parameters" field.
func FileParametersLTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFileParameters), v))
	})
}

// FileParametersContains applies the Contains predicate on the "file_parameters" field.
func FileParametersContains(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFileParameters), v))
	})
}

// FileParametersHasPrefix applies the HasPrefix predicate on the "file_parameters" field.
func FileParametersHasPrefix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFileParameters), v))
	})
}

// FileParametersHasSuffix applies the HasSuffix predicate on the "file_parameters" field.
func FileParametersHasSuffix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFileParameters), v))
	})
}

// FileParametersEqualFold applies the EqualFold predicate on the "file_parameters" field.
func FileParametersEqualFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFileParameters), v))
	})
}

// FileParametersContainsFold applies the ContainsFold predicate on the "file_parameters" field.
func FileParametersContainsFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFileParameters), v))
	})
}

// TotalMappingEQ applies the EQ predicate on the "total_mapping" field.
func TotalMappingEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTotalMapping), v))
	})
}

// TotalMappingNEQ applies the NEQ predicate on the "total_mapping" field.
func TotalMappingNEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTotalMapping), v))
	})
}

// TotalMappingIn applies the In predicate on the "total_mapping" field.
func TotalMappingIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTotalMapping), v...))
	})
}

// TotalMappingNotIn applies the NotIn predicate on the "total_mapping" field.
func TotalMappingNotIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTotalMapping), v...))
	})
}

// TotalMappingGT applies the GT predicate on the "total_mapping" field.
func TotalMappingGT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTotalMapping), v))
	})
}

// TotalMappingGTE applies the GTE predicate on the "total_mapping" field.
func TotalMappingGTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTotalMapping), v))
	})
}

// TotalMappingLT applies the LT predicate on the "total_mapping" field.
func TotalMappingLT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTotalMapping), v))
	})
}

// TotalMappingLTE applies the LTE predicate on the "total_mapping" field.
func TotalMappingLTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTotalMapping), v))
	})
}

// StatsTotalRowEQ applies the EQ predicate on the "stats_total_row" field.
func StatsTotalRowEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatsTotalRow), v))
	})
}

// StatsTotalRowNEQ applies the NEQ predicate on the "stats_total_row" field.
func StatsTotalRowNEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatsTotalRow), v))
	})
}

// StatsTotalRowIn applies the In predicate on the "stats_total_row" field.
func StatsTotalRowIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldStatsTotalRow), v...))
	})
}

// StatsTotalRowNotIn applies the NotIn predicate on the "stats_total_row" field.
func StatsTotalRowNotIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldStatsTotalRow), v...))
	})
}

// StatsTotalRowGT applies the GT predicate on the "stats_total_row" field.
func StatsTotalRowGT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatsTotalRow), v))
	})
}

// StatsTotalRowGTE applies the GTE predicate on the "stats_total_row" field.
func StatsTotalRowGTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatsTotalRow), v))
	})
}

// StatsTotalRowLT applies the LT predicate on the "stats_total_row" field.
func StatsTotalRowLT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatsTotalRow), v))
	})
}

// StatsTotalRowLTE applies the LTE predicate on the "stats_total_row" field.
func StatsTotalRowLTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatsTotalRow), v))
	})
}

// StatsTotalProcessedEQ applies the EQ predicate on the "stats_total_processed" field.
func StatsTotalProcessedEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatsTotalProcessed), v))
	})
}

// StatsTotalProcessedNEQ applies the NEQ predicate on the "stats_total_processed" field.
func StatsTotalProcessedNEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatsTotalProcessed), v))
	})
}

// StatsTotalProcessedIn applies the In predicate on the "stats_total_processed" field.
func StatsTotalProcessedIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldStatsTotalProcessed), v...))
	})
}

// StatsTotalProcessedNotIn applies the NotIn predicate on the "stats_total_processed" field.
func StatsTotalProcessedNotIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldStatsTotalProcessed), v...))
	})
}

// StatsTotalProcessedGT applies the GT predicate on the "stats_total_processed" field.
func StatsTotalProcessedGT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatsTotalProcessed), v))
	})
}

// StatsTotalProcessedGTE applies the GTE predicate on the "stats_total_processed" field.
func StatsTotalProcessedGTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatsTotalProcessed), v))
	})
}

// StatsTotalProcessedLT applies the LT predicate on the "stats_total_processed" field.
func StatsTotalProcessedLT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatsTotalProcessed), v))
	})
}

// StatsTotalProcessedLTE applies the LTE predicate on the "stats_total_processed" field.
func StatsTotalProcessedLTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatsTotalProcessed), v))
	})
}

// StatsTotalSuccessEQ applies the EQ predicate on the "stats_total_success" field.
func StatsTotalSuccessEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatsTotalSuccess), v))
	})
}

// StatsTotalSuccessNEQ applies the NEQ predicate on the "stats_total_success" field.
func StatsTotalSuccessNEQ(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatsTotalSuccess), v))
	})
}

// StatsTotalSuccessIn applies the In predicate on the "stats_total_success" field.
func StatsTotalSuccessIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldStatsTotalSuccess), v...))
	})
}

// StatsTotalSuccessNotIn applies the NotIn predicate on the "stats_total_success" field.
func StatsTotalSuccessNotIn(vs ...int32) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldStatsTotalSuccess), v...))
	})
}

// StatsTotalSuccessGT applies the GT predicate on the "stats_total_success" field.
func StatsTotalSuccessGT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatsTotalSuccess), v))
	})
}

// StatsTotalSuccessGTE applies the GTE predicate on the "stats_total_success" field.
func StatsTotalSuccessGTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatsTotalSuccess), v))
	})
}

// StatsTotalSuccessLT applies the LT predicate on the "stats_total_success" field.
func StatsTotalSuccessLT(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatsTotalSuccess), v))
	})
}

// StatsTotalSuccessLTE applies the LTE predicate on the "stats_total_success" field.
func StatsTotalSuccessLTE(v int32) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatsTotalSuccess), v))
	})
}

// ErrorDisplayEQ applies the EQ predicate on the "error_display" field.
func ErrorDisplayEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayNEQ applies the NEQ predicate on the "error_display" field.
func ErrorDisplayNEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayIn applies the In predicate on the "error_display" field.
func ErrorDisplayIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldErrorDisplay), v...))
	})
}

// ErrorDisplayNotIn applies the NotIn predicate on the "error_display" field.
func ErrorDisplayNotIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldErrorDisplay), v...))
	})
}

// ErrorDisplayGT applies the GT predicate on the "error_display" field.
func ErrorDisplayGT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayGTE applies the GTE predicate on the "error_display" field.
func ErrorDisplayGTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayLT applies the LT predicate on the "error_display" field.
func ErrorDisplayLT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayLTE applies the LTE predicate on the "error_display" field.
func ErrorDisplayLTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayContains applies the Contains predicate on the "error_display" field.
func ErrorDisplayContains(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayHasPrefix applies the HasPrefix predicate on the "error_display" field.
func ErrorDisplayHasPrefix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayHasSuffix applies the HasSuffix predicate on the "error_display" field.
func ErrorDisplayHasSuffix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayEqualFold applies the EqualFold predicate on the "error_display" field.
func ErrorDisplayEqualFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldErrorDisplay), v))
	})
}

// ErrorDisplayContainsFold applies the ContainsFold predicate on the "error_display" field.
func ErrorDisplayContainsFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldErrorDisplay), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedBy), v))
	})
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedBy), v))
	})
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedBy), v...))
	})
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedBy), v...))
	})
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedBy), v))
	})
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedBy), v))
	})
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedBy), v))
	})
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedBy), v))
	})
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCreatedBy), v))
	})
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCreatedBy), v))
	})
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCreatedBy), v))
	})
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCreatedBy), v))
	})
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCreatedBy), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProcessingFile {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProcessingFile) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProcessingFile) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProcessingFile) predicate.ProcessingFile {
	return predicate.ProcessingFile(func(s *sql.Selector) {
		p(s.Not())
	})
}
