// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FileAwardPointColumns holds the columns for the "file_award_point" table.
	FileAwardPointColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "merchant_id", Type: field.TypeInt64},
		{Name: "display_name", Type: field.TypeString},
		{Name: "file_url", Type: field.TypeString},
		{Name: "result_file_url", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt16, Default: 0},
		{Name: "stats_total_row", Type: field.TypeInt16, Default: 0},
		{Name: "stats_total_success", Type: field.TypeInt16, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString},
		{Name: "updated_by", Type: field.TypeString},
	}
	// FileAwardPointTable holds the schema information for the "file_award_point" table.
	FileAwardPointTable = &schema.Table{
		Name:       "file_award_point",
		Columns:    FileAwardPointColumns,
		PrimaryKey: []*schema.Column{FileAwardPointColumns[0]},
	}
	// MemberTransactionColumns holds the columns for the "member_transaction" table.
	MemberTransactionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "file_award_point_id", Type: field.TypeInt32},
		{Name: "point", Type: field.TypeInt64},
		{Name: "phone", Type: field.TypeString, Size: 15},
		{Name: "order_code", Type: field.TypeString, Size: 50},
		{Name: "ref_id", Type: field.TypeString, Size: 50},
		{Name: "sent_time", Type: field.TypeTime},
		{Name: "txn_desc", Type: field.TypeString, Size: 255},
		{Name: "status", Type: field.TypeInt16, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MemberTransactionTable holds the schema information for the "member_transaction" table.
	MemberTransactionTable = &schema.Table{
		Name:       "member_transaction",
		Columns:    MemberTransactionColumns,
		PrimaryKey: []*schema.Column{MemberTransactionColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "email", Type: field.TypeString},
		{Name: "phone_number", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FileAwardPointTable,
		MemberTransactionTable,
		UsersTable,
	}
)

func init() {
	FileAwardPointTable.Annotation = &entsql.Annotation{
		Table: "file_award_point",
	}
	MemberTransactionTable.Annotation = &entsql.Annotation{
		Table: "member_transaction",
	}
}
