// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/fileawardpoint"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/predicate"
)

// FileAwardPointDelete is the builder for deleting a FileAwardPoint entity.
type FileAwardPointDelete struct {
	config
	hooks    []Hook
	mutation *FileAwardPointMutation
}

// Where appends a list predicates to the FileAwardPointDelete builder.
func (fapd *FileAwardPointDelete) Where(ps ...predicate.FileAwardPoint) *FileAwardPointDelete {
	fapd.mutation.Where(ps...)
	return fapd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fapd *FileAwardPointDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fapd.hooks) == 0 {
		affected, err = fapd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileAwardPointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fapd.mutation = mutation
			affected, err = fapd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fapd.hooks) - 1; i >= 0; i-- {
			if fapd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fapd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fapd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (fapd *FileAwardPointDelete) ExecX(ctx context.Context) int {
	n, err := fapd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fapd *FileAwardPointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: fileawardpoint.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fileawardpoint.FieldID,
			},
		},
	}
	if ps := fapd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fapd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// FileAwardPointDeleteOne is the builder for deleting a single FileAwardPoint entity.
type FileAwardPointDeleteOne struct {
	fapd *FileAwardPointDelete
}

// Exec executes the deletion query.
func (fapdo *FileAwardPointDeleteOne) Exec(ctx context.Context) error {
	n, err := fapdo.fapd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fileawardpoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fapdo *FileAwardPointDeleteOne) ExecX(ctx context.Context) {
	fapdo.fapd.ExecX(ctx)
}
