// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/fileawardpoint"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/predicate"
)

// FileAwardPointQuery is the builder for querying FileAwardPoint entities.
type FileAwardPointQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.FileAwardPoint
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FileAwardPointQuery builder.
func (fapq *FileAwardPointQuery) Where(ps ...predicate.FileAwardPoint) *FileAwardPointQuery {
	fapq.predicates = append(fapq.predicates, ps...)
	return fapq
}

// Limit adds a limit step to the query.
func (fapq *FileAwardPointQuery) Limit(limit int) *FileAwardPointQuery {
	fapq.limit = &limit
	return fapq
}

// Offset adds an offset step to the query.
func (fapq *FileAwardPointQuery) Offset(offset int) *FileAwardPointQuery {
	fapq.offset = &offset
	return fapq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fapq *FileAwardPointQuery) Unique(unique bool) *FileAwardPointQuery {
	fapq.unique = &unique
	return fapq
}

// Order adds an order step to the query.
func (fapq *FileAwardPointQuery) Order(o ...OrderFunc) *FileAwardPointQuery {
	fapq.order = append(fapq.order, o...)
	return fapq
}

// First returns the first FileAwardPoint entity from the query.
// Returns a *NotFoundError when no FileAwardPoint was found.
func (fapq *FileAwardPointQuery) First(ctx context.Context) (*FileAwardPoint, error) {
	nodes, err := fapq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fileawardpoint.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fapq *FileAwardPointQuery) FirstX(ctx context.Context) *FileAwardPoint {
	node, err := fapq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FileAwardPoint ID from the query.
// Returns a *NotFoundError when no FileAwardPoint ID was found.
func (fapq *FileAwardPointQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fapq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fileawardpoint.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fapq *FileAwardPointQuery) FirstIDX(ctx context.Context) int {
	id, err := fapq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FileAwardPoint entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FileAwardPoint entity is found.
// Returns a *NotFoundError when no FileAwardPoint entities are found.
func (fapq *FileAwardPointQuery) Only(ctx context.Context) (*FileAwardPoint, error) {
	nodes, err := fapq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fileawardpoint.Label}
	default:
		return nil, &NotSingularError{fileawardpoint.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fapq *FileAwardPointQuery) OnlyX(ctx context.Context) *FileAwardPoint {
	node, err := fapq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FileAwardPoint ID in the query.
// Returns a *NotSingularError when more than one FileAwardPoint ID is found.
// Returns a *NotFoundError when no entities are found.
func (fapq *FileAwardPointQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fapq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fileawardpoint.Label}
	default:
		err = &NotSingularError{fileawardpoint.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fapq *FileAwardPointQuery) OnlyIDX(ctx context.Context) int {
	id, err := fapq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FileAwardPoints.
func (fapq *FileAwardPointQuery) All(ctx context.Context) ([]*FileAwardPoint, error) {
	if err := fapq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return fapq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (fapq *FileAwardPointQuery) AllX(ctx context.Context) []*FileAwardPoint {
	nodes, err := fapq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FileAwardPoint IDs.
func (fapq *FileAwardPointQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := fapq.Select(fileawardpoint.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fapq *FileAwardPointQuery) IDsX(ctx context.Context) []int {
	ids, err := fapq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fapq *FileAwardPointQuery) Count(ctx context.Context) (int, error) {
	if err := fapq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return fapq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (fapq *FileAwardPointQuery) CountX(ctx context.Context) int {
	count, err := fapq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fapq *FileAwardPointQuery) Exist(ctx context.Context) (bool, error) {
	if err := fapq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return fapq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (fapq *FileAwardPointQuery) ExistX(ctx context.Context) bool {
	exist, err := fapq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FileAwardPointQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fapq *FileAwardPointQuery) Clone() *FileAwardPointQuery {
	if fapq == nil {
		return nil
	}
	return &FileAwardPointQuery{
		config:     fapq.config,
		limit:      fapq.limit,
		offset:     fapq.offset,
		order:      append([]OrderFunc{}, fapq.order...),
		predicates: append([]predicate.FileAwardPoint{}, fapq.predicates...),
		// clone intermediate query.
		sql:    fapq.sql.Clone(),
		path:   fapq.path,
		unique: fapq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MerchantID int64 `json:"merchant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FileAwardPoint.Query().
//		GroupBy(fileawardpoint.FieldMerchantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fapq *FileAwardPointQuery) GroupBy(field string, fields ...string) *FileAwardPointGroupBy {
	grbuild := &FileAwardPointGroupBy{config: fapq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := fapq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return fapq.sqlQuery(ctx), nil
	}
	grbuild.label = fileawardpoint.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MerchantID int64 `json:"merchant_id,omitempty"`
//	}
//
//	client.FileAwardPoint.Query().
//		Select(fileawardpoint.FieldMerchantID).
//		Scan(ctx, &v)
func (fapq *FileAwardPointQuery) Select(fields ...string) *FileAwardPointSelect {
	fapq.fields = append(fapq.fields, fields...)
	selbuild := &FileAwardPointSelect{FileAwardPointQuery: fapq}
	selbuild.label = fileawardpoint.Label
	selbuild.flds, selbuild.scan = &fapq.fields, selbuild.Scan
	return selbuild
}

func (fapq *FileAwardPointQuery) prepareQuery(ctx context.Context) error {
	for _, f := range fapq.fields {
		if !fileawardpoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fapq.path != nil {
		prev, err := fapq.path(ctx)
		if err != nil {
			return err
		}
		fapq.sql = prev
	}
	return nil
}

func (fapq *FileAwardPointQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FileAwardPoint, error) {
	var (
		nodes = []*FileAwardPoint{}
		_spec = fapq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*FileAwardPoint).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &FileAwardPoint{config: fapq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fapq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fapq *FileAwardPointQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fapq.querySpec()
	_spec.Node.Columns = fapq.fields
	if len(fapq.fields) > 0 {
		_spec.Unique = fapq.unique != nil && *fapq.unique
	}
	return sqlgraph.CountNodes(ctx, fapq.driver, _spec)
}

func (fapq *FileAwardPointQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := fapq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (fapq *FileAwardPointQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fileawardpoint.Table,
			Columns: fileawardpoint.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fileawardpoint.FieldID,
			},
		},
		From:   fapq.sql,
		Unique: true,
	}
	if unique := fapq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fapq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fileawardpoint.FieldID)
		for i := range fields {
			if fields[i] != fileawardpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fapq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fapq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fapq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fapq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fapq *FileAwardPointQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fapq.driver.Dialect())
	t1 := builder.Table(fileawardpoint.Table)
	columns := fapq.fields
	if len(columns) == 0 {
		columns = fileawardpoint.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fapq.sql != nil {
		selector = fapq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fapq.unique != nil && *fapq.unique {
		selector.Distinct()
	}
	for _, p := range fapq.predicates {
		p(selector)
	}
	for _, p := range fapq.order {
		p(selector)
	}
	if offset := fapq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fapq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FileAwardPointGroupBy is the group-by builder for FileAwardPoint entities.
type FileAwardPointGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fapgb *FileAwardPointGroupBy) Aggregate(fns ...AggregateFunc) *FileAwardPointGroupBy {
	fapgb.fns = append(fapgb.fns, fns...)
	return fapgb
}

// Scan applies the group-by query and scans the result into the given value.
func (fapgb *FileAwardPointGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := fapgb.path(ctx)
	if err != nil {
		return err
	}
	fapgb.sql = query
	return fapgb.sqlScan(ctx, v)
}

func (fapgb *FileAwardPointGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fapgb.fields {
		if !fileawardpoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fapgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fapgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fapgb *FileAwardPointGroupBy) sqlQuery() *sql.Selector {
	selector := fapgb.sql.Select()
	aggregation := make([]string, 0, len(fapgb.fns))
	for _, fn := range fapgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(fapgb.fields)+len(fapgb.fns))
		for _, f := range fapgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(fapgb.fields...)...)
}

// FileAwardPointSelect is the builder for selecting fields of FileAwardPoint entities.
type FileAwardPointSelect struct {
	*FileAwardPointQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (faps *FileAwardPointSelect) Scan(ctx context.Context, v interface{}) error {
	if err := faps.prepareQuery(ctx); err != nil {
		return err
	}
	faps.sql = faps.FileAwardPointQuery.sqlQuery(ctx)
	return faps.sqlScan(ctx, v)
}

func (faps *FileAwardPointSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := faps.sql.Query()
	if err := faps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
