// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/predicate"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/processingfilerow"
)

// ProcessingFileRowDelete is the builder for deleting a ProcessingFileRow entity.
type ProcessingFileRowDelete struct {
	config
	hooks    []Hook
	mutation *ProcessingFileRowMutation
}

// Where appends a list predicates to the ProcessingFileRowDelete builder.
func (pfrd *ProcessingFileRowDelete) Where(ps ...predicate.ProcessingFileRow) *ProcessingFileRowDelete {
	pfrd.mutation.Where(ps...)
	return pfrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pfrd *ProcessingFileRowDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pfrd.hooks) == 0 {
		affected, err = pfrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProcessingFileRowMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pfrd.mutation = mutation
			affected, err = pfrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pfrd.hooks) - 1; i >= 0; i-- {
			if pfrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pfrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pfrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfrd *ProcessingFileRowDelete) ExecX(ctx context.Context) int {
	n, err := pfrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pfrd *ProcessingFileRowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: processingfilerow.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: processingfilerow.FieldID,
			},
		},
	}
	if ps := pfrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pfrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ProcessingFileRowDeleteOne is the builder for deleting a single ProcessingFileRow entity.
type ProcessingFileRowDeleteOne struct {
	pfrd *ProcessingFileRowDelete
}

// Exec executes the deletion query.
func (pfrdo *ProcessingFileRowDeleteOne) Exec(ctx context.Context) error {
	n, err := pfrdo.pfrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{processingfilerow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pfrdo *ProcessingFileRowDeleteOne) ExecX(ctx context.Context) {
	pfrdo.pfrd.ExecX(ctx)
}
