// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/fileawardpoint"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/membertransaction"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/processingfile"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/ent/user"
	"git.teko.vn/loyalty-system/loyalty-file-processing/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileawardpointFields := schema.FileAwardPoint{}.Fields()
	_ = fileawardpointFields
	// fileawardpointDescDisplayName is the schema descriptor for display_name field.
	fileawardpointDescDisplayName := fileawardpointFields[1].Descriptor()
	// fileawardpoint.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	fileawardpoint.DisplayNameValidator = fileawardpointDescDisplayName.Validators[0].(func(string) error)
	// fileawardpointDescFileURL is the schema descriptor for file_url field.
	fileawardpointDescFileURL := fileawardpointFields[2].Descriptor()
	// fileawardpoint.FileURLValidator is a validator for the "file_url" field. It is called by the builders before save.
	fileawardpoint.FileURLValidator = func() func(string) error {
		validators := fileawardpointDescFileURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_url string) error {
			for _, fn := range fns {
				if err := fn(file_url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fileawardpointDescResultFileURL is the schema descriptor for result_file_url field.
	fileawardpointDescResultFileURL := fileawardpointFields[3].Descriptor()
	// fileawardpoint.ResultFileURLValidator is a validator for the "result_file_url" field. It is called by the builders before save.
	fileawardpoint.ResultFileURLValidator = fileawardpointDescResultFileURL.Validators[0].(func(string) error)
	// fileawardpointDescNote is the schema descriptor for note field.
	fileawardpointDescNote := fileawardpointFields[4].Descriptor()
	// fileawardpoint.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	fileawardpoint.NoteValidator = fileawardpointDescNote.Validators[0].(func(string) error)
	// fileawardpointDescStatus is the schema descriptor for status field.
	fileawardpointDescStatus := fileawardpointFields[5].Descriptor()
	// fileawardpoint.DefaultStatus holds the default value on creation for the status field.
	fileawardpoint.DefaultStatus = fileawardpointDescStatus.Default.(int16)
	// fileawardpointDescStatsTotalRow is the schema descriptor for stats_total_row field.
	fileawardpointDescStatsTotalRow := fileawardpointFields[6].Descriptor()
	// fileawardpoint.DefaultStatsTotalRow holds the default value on creation for the stats_total_row field.
	fileawardpoint.DefaultStatsTotalRow = fileawardpointDescStatsTotalRow.Default.(int32)
	// fileawardpointDescStatsTotalSuccess is the schema descriptor for stats_total_success field.
	fileawardpointDescStatsTotalSuccess := fileawardpointFields[7].Descriptor()
	// fileawardpoint.DefaultStatsTotalSuccess holds the default value on creation for the stats_total_success field.
	fileawardpoint.DefaultStatsTotalSuccess = fileawardpointDescStatsTotalSuccess.Default.(int32)
	// fileawardpointDescCreatedAt is the schema descriptor for created_at field.
	fileawardpointDescCreatedAt := fileawardpointFields[8].Descriptor()
	// fileawardpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	fileawardpoint.DefaultCreatedAt = fileawardpointDescCreatedAt.Default.(func() time.Time)
	// fileawardpointDescUpdatedAt is the schema descriptor for updated_at field.
	fileawardpointDescUpdatedAt := fileawardpointFields[9].Descriptor()
	// fileawardpoint.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fileawardpoint.DefaultUpdatedAt = fileawardpointDescUpdatedAt.Default.(func() time.Time)
	// fileawardpoint.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fileawardpoint.UpdateDefaultUpdatedAt = fileawardpointDescUpdatedAt.UpdateDefault.(func() time.Time)
	membertransactionFields := schema.MemberTransaction{}.Fields()
	_ = membertransactionFields
	// membertransactionDescPhone is the schema descriptor for phone field.
	membertransactionDescPhone := membertransactionFields[2].Descriptor()
	// membertransaction.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	membertransaction.PhoneValidator = func() func(string) error {
		validators := membertransactionDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// membertransactionDescOrderCode is the schema descriptor for order_code field.
	membertransactionDescOrderCode := membertransactionFields[3].Descriptor()
	// membertransaction.OrderCodeValidator is a validator for the "order_code" field. It is called by the builders before save.
	membertransaction.OrderCodeValidator = membertransactionDescOrderCode.Validators[0].(func(string) error)
	// membertransactionDescRefID is the schema descriptor for ref_id field.
	membertransactionDescRefID := membertransactionFields[4].Descriptor()
	// membertransaction.RefIDValidator is a validator for the "ref_id" field. It is called by the builders before save.
	membertransaction.RefIDValidator = membertransactionDescRefID.Validators[0].(func(string) error)
	// membertransactionDescSentTime is the schema descriptor for sent_time field.
	membertransactionDescSentTime := membertransactionFields[5].Descriptor()
	// membertransaction.DefaultSentTime holds the default value on creation for the sent_time field.
	membertransaction.DefaultSentTime = membertransactionDescSentTime.Default.(time.Time)
	// membertransactionDescLoyaltyTxnID is the schema descriptor for loyalty_txn_id field.
	membertransactionDescLoyaltyTxnID := membertransactionFields[6].Descriptor()
	// membertransaction.DefaultLoyaltyTxnID holds the default value on creation for the loyalty_txn_id field.
	membertransaction.DefaultLoyaltyTxnID = membertransactionDescLoyaltyTxnID.Default.(int64)
	// membertransactionDescTxnDesc is the schema descriptor for txn_desc field.
	membertransactionDescTxnDesc := membertransactionFields[7].Descriptor()
	// membertransaction.TxnDescValidator is a validator for the "txn_desc" field. It is called by the builders before save.
	membertransaction.TxnDescValidator = membertransactionDescTxnDesc.Validators[0].(func(string) error)
	// membertransactionDescStatus is the schema descriptor for status field.
	membertransactionDescStatus := membertransactionFields[8].Descriptor()
	// membertransaction.DefaultStatus holds the default value on creation for the status field.
	membertransaction.DefaultStatus = membertransactionDescStatus.Default.(int16)
	// membertransactionDescError is the schema descriptor for error field.
	membertransactionDescError := membertransactionFields[9].Descriptor()
	// membertransaction.ErrorValidator is a validator for the "error" field. It is called by the builders before save.
	membertransaction.ErrorValidator = membertransactionDescError.Validators[0].(func(string) error)
	// membertransactionDescCreatedAt is the schema descriptor for created_at field.
	membertransactionDescCreatedAt := membertransactionFields[10].Descriptor()
	// membertransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	membertransaction.DefaultCreatedAt = membertransactionDescCreatedAt.Default.(time.Time)
	// membertransactionDescUpdatedAt is the schema descriptor for updated_at field.
	membertransactionDescUpdatedAt := membertransactionFields[11].Descriptor()
	// membertransaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membertransaction.DefaultUpdatedAt = membertransactionDescUpdatedAt.Default.(time.Time)
	processingfileFields := schema.ProcessingFile{}.Fields()
	_ = processingfileFields
	// processingfileDescDisplayName is the schema descriptor for display_name field.
	processingfileDescDisplayName := processingfileFields[1].Descriptor()
	// processingfile.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	processingfile.DisplayNameValidator = processingfileDescDisplayName.Validators[0].(func(string) error)
	// processingfileDescFileURL is the schema descriptor for file_url field.
	processingfileDescFileURL := processingfileFields[2].Descriptor()
	// processingfile.FileURLValidator is a validator for the "file_url" field. It is called by the builders before save.
	processingfile.FileURLValidator = processingfileDescFileURL.Validators[0].(func(string) error)
	// processingfileDescCreatedAt is the schema descriptor for created_at field.
	processingfileDescCreatedAt := processingfileFields[8].Descriptor()
	// processingfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	processingfile.DefaultCreatedAt = processingfileDescCreatedAt.Default.(func() time.Time)
	// processingfileDescCreatedBy is the schema descriptor for created_by field.
	processingfileDescCreatedBy := processingfileFields[9].Descriptor()
	// processingfile.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	processingfile.CreatedByValidator = processingfileDescCreatedBy.Validators[0].(func(string) error)
	// processingfileDescUpdatedAt is the schema descriptor for updated_at field.
	processingfileDescUpdatedAt := processingfileFields[10].Descriptor()
	// processingfile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	processingfile.DefaultUpdatedAt = processingfileDescUpdatedAt.Default.(func() time.Time)
	// processingfile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	processingfile.UpdateDefaultUpdatedAt = processingfileDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[1].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
}
